// <auto-generated />
using System;
using Hogwarts.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hogwarts.DataAccess.Migrations
{
    [DbContext(typeof(HowartsContext))]
    partial class HowartsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Hogwarts.DataAccess.Entities.AdmissionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("Age")
                        .HasMaxLength(10)
                        .HasColumnType("smallint");

                    b.Property<Guid>("HouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("HouseId");

                    b.ToTable("AdmissionRequest");
                });

            modelBuilder.Entity("Hogwarts.DataAccess.Entities.House", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("House");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11e6f800-a51d-4981-bd1b-a7ce662323b7"),
                            Name = "Gryffindor"
                        },
                        new
                        {
                            Id = new Guid("d4345b32-b146-41b4-ab0c-53e82c47d07e"),
                            Name = "Hufflepuff"
                        },
                        new
                        {
                            Id = new Guid("0f444e63-249c-4f72-a031-d5df767fa456"),
                            Name = "Ravenclaw"
                        },
                        new
                        {
                            Id = new Guid("a01844d7-e79a-475d-b87d-91dd55776e0f"),
                            Name = "Slytherin"
                        });
                });

            modelBuilder.Entity("Hogwarts.DataAccess.Entities.AdmissionRequest", b =>
                {
                    b.HasOne("Hogwarts.DataAccess.Entities.House", "House")
                        .WithMany()
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("House");
                });
#pragma warning restore 612, 618
        }
    }
}
